name: Compile

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  documentation:
    name: Documentation with Paradox
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: "Create site with Paradox"
        run: cd docs && sbt makeSite

#      - name: Run Link Validator
#        run: cs launch net.runne::site-link-validator:0.2.2 -- scripts/link-validator.conf

  samples:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { directory: ftp-to-file }
          - { directory: http-csv-to-kafka }
          - { directory: jdbc-to-elasticsearch }
          - { directory: jms }
          - { directory: kafka-to-websocket-clients }
          - { directory: kafka-to-elasticsearch }
          - { directory: mqtt-to-kafka }
          - { directory: file-to-elasticsearch }
          - { directory: mqtt-http-to-s3-java }
          - { directory: sqs-java }
          - { directory: rotate-logs-to-ftp }

    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: ${{ matrix.directory }}
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: cd pekko-connectors-sample-${DIRECTORY} && sbt compile
